<a href="https://colab.research.google.com/github/lakshmikanthgr/Complete-DSA-Python/blob/main/01_Python_Basics_for_DSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics for DSA

In [ ]:
print("Hello!!, Welecome to Python Basics for DSA!")

Hello!!, Welecome to Python Basics for DSA!


# List comprehensions

List compressions are concise way of creating, tranforming or filtering the list.


1. Creating a list.
2. Transforming a list
3. Filterning a list
4. Nested loop in list comprehension
5. Flatterning 2d(nested list) to 1d list
6. Using functions in List Comprehension

In [79]:
# Example: Creating a basic list
# Generating a list of squares for first n natural numbers
squares = [x**2 for x in range(10)]
print(squares)



[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [78]:
# Example: Transforming a list
# Convert all the words in the list into titles(First letter has to be Capital)
words = ["hello", "world", "welcome", "dsa", "in", "python"]
titlewords = [word.title() for word in words]
print(titlewords)



['Hello', 'World', 'Welcome', 'Dsa', 'In', 'Python']


In [77]:
# Example: Filter a list
# Find the even number in the given range
even_numbers = [i for i in range(10) if i%2 == 0]
print(even_numbers)



[0, 2, 4, 6, 8]


In [76]:
# Nested loops in list comprehension
list_a = [1,2,3]
list_b = ['a','b','c']

combination_list = [(a,b) for a in list_a for b in list_b]
print(combination_list)



[(1, 'a'), (1, 'b'), (1, 'c'), (2, 'a'), (2, 'b'), (2, 'c'), (3, 'a'), (3, 'b'), (3, 'c')]


In [75]:
#Example: Nested list: 2D to 1D conversion
list_2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]

list_1d = [item for sub_list in list_2d for item in sub_list]
print(list_1d)

#Example: Using functions in the list comprehensions
def isprime(n):
  for i in range(2,n):
    if (n%i)==0:
      return False
  return True

prime_number_bools = [isprime(x) for x in range(2,50)]
print(prime_number_bools)
print(len([pr for pr in prime_number_bools if pr == True]))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[True, True, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, True, False, False]
15


# Generators and Iterators

This are the tools in python to efficiently handle the datastream ans sequences.
They allows processing one at a time. This is very usefull while dealing with big/huge dataseets.

## iterator
Iterator is an object that allows sequential access to the sequence(Dictionaries, strings) or a collection(List, tuples, sets)
1. __iter__() Returns the iterator object itself.
2. __next__() Returns the next item in the sequence or raise `stopItetation` .exception

## Generator
A generator is a special type of iterator defined using a function with `yield` statement. Unlike function that returns single value at the end, Generator yields one value at a time, pause execution between values.

Generators are very usefull while dealing with large amount of data.

In [80]:
# Iterator

list_normal = [1,231,31,41,4212]
list_iterator = iter(list_normal)
print(type(list_normal))
print(type(list_iterator))

print(next(list_iterator))
print(next(list_iterator))

# Below code raise an exception that TypeError:
#'list' object is not an iterator
#print(next(list_normal))




<class 'list'>
<class 'list_iterator'>
1
231


In [81]:
# Generator

# Example: Generator for infinite set of fibanocci
def fibanocci():
  a,b = 0,1
  while True:
    yield a
    b,a = a+b,b

fib = fibanocci()
print(type(fib))
print(next(fib))
print(next(fib))

for _ in range(10):
  print(next(fib),end = " ")
print("\n")



# File Processing with Generators
# def read_large_file(file_path):
#     with open(file_path, 'r') as file:
#         for line in file:
#             yield line.strip()

# for line in read_large_file('large_file.txt'):
#     print(line)
# Processes one line at a time, reducing memory usage.


<class 'generator'>
0
1
1 2 3 5 8 13 21 34 55 89 



In [82]:
# Example: You can make a generator as list comprehension too.
# Here you will use () instead of []

list_normal = [x**2 for x in range(2,20)]
print(f"Type of list_normal {type(list_normal)} and the lis is {list_normal}")

list_gen = (x**2 for x in range(2,20))
print(f"Type of list_gen  {type(list_gen)} and next elemt is {next(list_gen)}")



Type of list_normal <class 'list'> and the lis is [4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
Type of list_gen  <class 'generator'> and next elemt is 4


In [ ]:
#Example: Chaining Generator: Using one generator as a input for other.
def double_value(nums):
  for n in nums:
    yield n*n

nums = range(11)
print(nums)
for x in double_value(nums):
  print(x,end= " ")

# Lambda Functions

Lambda functions are anonymous and single liner simple function defined using keyword `lambda`. These functions typically used when a small, throwaway function is needed for a short time.

In [18]:
# Example add
add = lambda x,y: x+y
print(add(1131,231))

# Examaple: Sorting list of tuple by second element:
data = [(1,'B'),(2,'A'),(3,'C')]

# Conventional way without using lamda function.
# using Named function:

def sort_key(item):
  return item[1]
sort_data_normal = sorted(data, key=sort_key)

print(sort_data_normal)

# By using lambda
sort_data_lambda = sorted(data, key = lambda x:x[1])
print(sort_data_lambda)

# Example: Filtering with lamda:
# Retun just even numbers from a list
import random
random.seed(2)
random_list = []
for i in range(50):
  random_list.append(random.randint(1,100))
print(random_list)
list_even_numbers = list(filter(lambda x: x%2==0, random_list))
print(list_even_numbers)


1362
[(2, 'A'), (1, 'B'), (3, 'C')]
[(2, 'A'), (1, 'B'), (3, 'C')]
[8, 12, 11, 47, 22, 95, 86, 40, 33, 78, 28, 78, 5, 75, 88, 21, 56, 82, 51, 93, 66, 48, 70, 57, 65, 35, 5, 4, 47, 60, 41, 49, 55, 68, 22, 72, 23, 31, 30, 4, 23, 42, 23, 18, 66, 66, 47, 66, 87, 72]
[8, 12, 22, 86, 40, 78, 28, 78, 88, 56, 82, 66, 48, 70, 4, 60, 68, 22, 72, 30, 4, 42, 18, 66, 66, 66, 72]


# Functional Programming

Functional programming is a paradigm in which the computation treated as evalution of mathematical functions.
It emphasizes immutability, first class functions and higer order functions.

1. **Immutability:**  Avoid modifying the data: instead, create new data structures.
2. **First-Class Functions:**  Functions that are treated as first class citizens and can be assigned to variables, Passed as arguments and returned from other functions.
3. **Higher-Order Functions:** Functions that takes functions as input or returns functions as output

## Common functional programming tools:
  *map, zip, filter, reduce, zip*


# NOTE: Dont use if you wanted to debug the logic or for complex logics and need documentations.


In [83]:
numbers = [12,121,31,52,212]

# Example: Map()
# Applies a functiion to each item in iterable:
squared = list(map(lambda x:x*x,numbers))
print(squared)



[144, 14641, 961, 2704, 44944]


In [84]:
# Example: Filter()
# Filters itens in an iterables based on the function return True or False
filter_even = list(filter(lambda x:x%2==0,numbers))
print(filter_even)



[12, 52, 212]


In [87]:
# Example: Reduce()
# Reduce from functools will reduce an iterable to a single value by applying
# function cumulatively
from functools import reduce

product_list = reduce(lambda x, y: x*y, numbers)
print(product_list)




496212288


In [86]:
# Zip()
# Combines two or more iterables into a tuple

names = ["Laks", "Moni", "Dhanshitha", "S__"]
ages = [34,30,1, -2]

combiner_list = list(zip(names, ages))
print(combiner_list)



[('Laks', 34), ('Moni', 30), ('Dhanshitha', 1), ('S__', -2)]


In [85]:
# Some more examples:
# Creating a list of squared values for even numbers:
squared_even = list(map(lambda x: x**2, filter(lambda x: x%2 == 0,numbers)))
print(squared_even)

[144, 2704, 44944]


# Working with NumPy Arrays for Efficiency

**numpy** is a powerfull python library used for numerical computing. It provides a high performance multi-dimensional array objec called ***ndarray*** and tools to work with those arrays efficiently. **Numpy** is backbone for many scientific computing and data analysis libraries.

## Why numpy for efficiency
1. **Optimized performance:** Numpy arrays are implemented in C, this makes them faster than python list for computational work.
2. **Memory efficient:** This consumes less memory than python lists.
3. **Vectorized Operations:** Numpy arrays allows you to perform element wise operations without using loops. That makes the code clean and concise.
4. **Convenience:** It provides lot of tool for data manipulations, for statistics and for all scintific computations.

## Key featurs of Numpy arrays
1. Homogenous data: All the elments in the ndarray must be same type
2. Multi-dimentional array: Suppors 1..n dimensions.
3. Broadcasting: Ability to perfom operations on array of different shapes.
4. Slicing and Indexing: Advanced way of accessing and modifying the array data.


In [28]:
# Example: Create a numpy array from List:

import numpy as np

arr_1d = np.array([1,23,31,32])
print(f"1-D array is {arr_1d}")

arr_2d = np.array([[1,31,22],[3,234432,3]])
print(f"2-D array is {arr_2d}")

1-D array is [ 1 23 31 32]
2-D array is [[     1     31     22]
 [     3 234432      3]]


In [35]:
# Example: Create an numpy array using built-in functions
import numpy as np


#help(np.zeros)
all_zeros = np.zeros((3,5),float)
print(f"All zero array is {all_zeros}")

all_ones = np.ones((3,12),str)
print(f"All ones as string is {all_ones}")

all_random=np.arange(1,13,2)
print(f"All random is {all_random}")


All zero array is [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
All ones as string is [['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']]
All random is [ 1  3  5  7  9 11]


In [37]:
# Element wise operations:
import numpy as np

# Multiple every element in list with 2
list_a = [12,22,31,4,12]


#Normal approach
list_normal = [x*2 for x in list_a]
print(list_normal)

n_arr = np.array(list_a)
print(n_arr*2)


[24, 44, 62, 8, 24]
[24 44 62  8 24]


In [41]:
# Broadcasting: Operations on different shape of arrays
# Need to spend some more tim in understanding broadcasting

import numpy as np

list_n = [2,24,34,23]

arr_n = np.array(list_n)
# Adding a scaler to every element
print(arr_n+5)

list_m = [[2],[311],[4]]
arr_m = np.array(list_m)
print(f"Shape of arr_n is {arr_n.shape} and arr_m is {arr_m.shape}")
print(arr_n + arr_m)

[ 7 29 39 28]
Shape of arr_n is (4,) and arr_m is (3, 1)
[[  4  26  36  25]
 [313 335 345 334]
 [  6  28  38  27]]


In [62]:
import numpy as np

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f"Shape of given {arr_2d} is {arr_2d.shape}")
#index starts from 0
print(f"Seocnd row third element is {arr_2d[1,2]}")
print(f"Second row array of arr_2d is {arr_2d[1]}")
print(f"Third column array of arr_2d is {arr_2d[:,2]}")
print(f"Sub array {arr_2d[1:,2:]} and its shape is {arr_2d[1:,2:].shape}")

Shape of given [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] is (4, 3)
Seocnd row third element is 6
Second row array of arr_2d is [4 5 6]
Third column array of arr_2d is [ 3  6  9 12]
Sub array [[ 6]
 [ 9]
 [12]] and its shape is (3, 1)


In [66]:
import numpy as np

A = np.array([[1,2],[2,4]])
B = np.array([[5,10],[10,5]])

AB = np.dot(A,B)

print(f"Dot product is {AB}")

Dot product is [[25 20]
 [50 40]]


In [68]:
import numpy as np

# finding minimu max and mean

A = np.array([1,23,41,41,41,45,6,134,3])
print(f"A Min is {A.min()} Max is {A.max()} and Mean is {A.mean()}")

A Min is 1 Max is 134 and Mean is 37.22222222222222


In [72]:
import numpy as np

# Boolean Indexing:
A = np.array([12,31,333,41,3,45])
B = A[A>30]
print(B)

#Reshaping tha array
print(f"The shape of A is {A.shape}")
A = A.reshape(2,3)
print(f"After reshape A is {A}  and its shape is {A.shape}")

[ 31 333  41  45]
The shape of A is (6,)
After reshape A is [[ 12  31 333]
 [ 41   3  45]]  and its shape is (2, 3)
